version: "3"
services:

  work:
    image: ghcr.io/kengo-k/dev-base-ubuntu:202304021230-09bb6ae
    container_name: study-ruest
    hostname: study-rust
    tty: true
    volumes:
      - ./:/workspace